version: "3.9"
services:
  redis:
    image: redis:6.2.5-alpine3.14
    container_name: redis
    environment:
      TZ: Asia/Tokyo
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
